version: '3.8'

volumes:
  postgres_data:
  static_files:
  media_files:

services:
  db:
    image: postgres:12.4
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build: timrock/yamdb_final:latest
    restart: always
    volumes:
      - static_files:/code/static
      - media_files:/code/media
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: library/nginx:1.19.6
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_files:/code/static/
      - media_files:/code/media/
    ports:
    - "80:80"
    depends_on:
      - web
